Milestone 1: Blog app - creating a data model
prg-04/blog_app pull request #1
Opened 2023-11-02 11:18 UTC by prg-04

### I have done the following to reach this milestone:

- [ ] Created a new app and gave it a meaningful name.
- [ ] Initialized my project with Git.
- [ ] Made sure that my project has Postgres database set up.
- [ ] Built my project schema.
- [ ] Created and ran the necessary migration files.

2023-11-02 12:15 UTC, TadesseDev requested changes
### Hi @prg-04 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)




## Highlights
 - [x] All the tables are created. ✅
 - [x] Good job overall following the template design ✅
 - [x] You have written a clean code ✅
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-02 12:15 UTC, TadesseDev commented on db/migrate/20231102091830_create_posts.rb
> +      t.integer :AuthorId
- [ ] Dear @prg-04, Good job creating the `posts` table, but according to the [given ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd_v1_1.png) you can see a post belongs to an author. we need to reflect this in our design, hence the `AuthorId` should be a foreign key from the `users` table.

2023-11-02 12:15 UTC, TadesseDev commented on db/migrate/20231102092318_create_comments.rb
> +      t.integer :PostId
- [ ] Dear @prg-04, same here. As you can see from the [given ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd_v1_1.png) `comment` belongs to a `user` and a `post`, hence the `UserId` and the `PostId` should be a foreign key from the `users` and `posts` tables. Please make sure the associations are preserved in your design.

2023-11-02 12:15 UTC, TadesseDev commented on db/migrate/20231102092216_create_likes.rb
> +      t.integer :PostId
- [ ] Same here, `UserId` and `PostId` are expected to be foreign keys from the `user` and `posts` table. This is to make sure you are following the ERD diagram closely.

2023-11-03 19:25 UTC, franclobo approved these changes
Hi @prg-04, 

# STATUS: APPROVED 😃 

![git-merge](https://github.com/prg-04/blog_app/assets/58642949/b6111230-e864-46ef-86e9-bcc050b5e220)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Correct migrations ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-03 19:25 UTC, franclobo commented on db/migrate/20231102090433_create_users.rb
> +end
- **[OPTIONAL]** Please 🙏🏽 review the [conventions](https://guides.rubyonrails.org/active_record_basics.html#naming-conventions) to avoid errors on your code in a future.

2023-11-03 19:25 UTC, franclobo commented on db/migrate/20231102091830_create_posts.rb
> +end
- **[OPTIONAL]** Please 🙏🏽 review the [conventions](https://guides.rubyonrails.org/active_record_basics.html#naming-conventions) to avoid errors on your code in a future.

2023-11-03 19:25 UTC, franclobo commented on db/migrate/20231102092216_create_likes.rb
> +end
- **[OPTIONAL]** Please 🙏🏽 review the [conventions](https://guides.rubyonrails.org/active_record_basics.html#naming-conventions) to avoid errors on your code in a future.

2023-11-03 19:25 UTC, franclobo commented on db/migrate/20231102092318_create_comments.rb
> +end
- **[OPTIONAL]** Please 🙏🏽 review the [conventions](https://guides.rubyonrails.org/active_record_basics.html#naming-conventions) to avoid errors on your code in a future.

2023-11-04 14:16 UTC, merged